# Generated by Django 4.2.21 on 2025-07-03 07:29

from django.db import migrations, models
import streaming_site_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingPeriod',
            fields=[
                ('id', models.CharField(default=streaming_site_list.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제시간', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제여부')),
                ('song_id', models.CharField(help_text='노래 ID', max_length=32)),
                ('start_date', models.DateField(help_text='크롤링 시작일')),
                ('end_date', models.DateField(help_text='크롤링 종료일')),
                ('is_active', models.BooleanField(default=True, help_text='활성화 여부')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.CharField(default=streaming_site_list.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제시간', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제여부')),
                ('song_id', models.CharField(help_text='노래 고유 ID', max_length=32, unique=True)),
                ('artist_name', models.CharField(help_text='아티스트명', max_length=255)),
                ('song_name', models.CharField(help_text='곡명', max_length=255)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL', max_length=500, null=True)),
            ],
            options={
                'unique_together': {('artist_name', 'song_name')},
            },
        ),
    ]
