# Generated by Django 4.2.21 on 2025-06-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '크롤링 자동 실행 버튼',
                'verbose_name_plural': '크롤링 자동 실행 버튼',
            },
        ),
    ]
