# Generated by Django 4.2.21 on 2025-07-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songinfo',
            name='genie_artist',
            field=models.CharField(blank=True, help_text='지니 아티스트명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='genie_title',
            field=models.CharField(blank=True, help_text='지니 곡 제목', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='melon_artist',
            field=models.CharField(blank=True, help_text='멜론 아티스트명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='melon_title',
            field=models.CharField(blank=True, help_text='멜론 곡 제목', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='youtube_artist',
            field=models.CharField(blank=True, help_text='유튜브 아티스트명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='youtube_music_artist',
            field=models.CharField(blank=True, help_text='유튜브 뮤직 아티스트명', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='youtube_music_title',
            field=models.CharField(blank=True, help_text='유튜브 뮤직 곡 제목', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='songinfo',
            name='youtube_title',
            field=models.CharField(blank=True, help_text='유튜브 곡 제목', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='artist',
            field=models.CharField(help_text='기본 아티스트명', max_length=255),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='title',
            field=models.CharField(help_text='기본 곡 제목', max_length=255),
        ),
    ]
