# Generated by Django 4.2.21 on 2025-07-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawlingperiod',
            table='crawling_period',
        ),
        migrations.AlterModelTable(
            name='songinfo',
            table='song_info',
        ),
    ]
