# Generated by Django 4.2.21 on 2025-07-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0002_alter_crawlingperiod_table_alter_songinfo_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinfo',
            name='song_id',
        ),
    ]
