# Generated by Django 4.2.21 on 2025-07-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0002_songinfo_genie_artist_songinfo_genie_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songinfo',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='melon_song_id',
            field=models.CharField(blank=True, help_text='멜론 곡 ID', max_length=100, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='songinfo',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='songinfo',
            name='title',
        ),
    ]
