# Generated by Django 4.2.21 on 2025-07-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0003_remove_songinfo_song_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlingperiod',
            name='is_active',
        ),
    ]
