# Generated by Django 4.2.21 on 2025-07-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_site_list', '0003_alter_songinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songinfo',
            name='melon_artist',
        ),
        migrations.RemoveField(
            model_name='songinfo',
            name='melon_title',
        ),
        migrations.RemoveField(
            model_name='songinfo',
            name='youtube_artist',
        ),
        migrations.RemoveField(
            model_name='songinfo',
            name='youtube_title',
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='melon_song_id',
            field=models.CharField(blank=True, help_text='멜론 곡 ID (Melon 크롤링용)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='songinfo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube URL (YouTube 크롤링용)', max_length=500, null=True),
        ),
    ]
