# Generated by Django 4.2.21 on 2025-07-03 07:32

from django.db import migrations, models
import streaming_site_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSongViewCount',
            fields=[
                ('id', models.CharField(default=streaming_site_list.models.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제시간', null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제여부')),
                ('song_id', models.CharField(help_text='노래 ID', max_length=32)),
                ('video_id', models.CharField(help_text='YouTube 비디오 ID', max_length=50)),
                ('view_count', models.BigIntegerField(default=0, help_text='조회수')),
                ('upload_date', models.DateField(help_text='업로드 날짜')),
                ('extracted_date', models.DateField(help_text='크롤링 실행 날짜')),
            ],
            options={
                'ordering': ['-extracted_date', '-created_at'],
                'unique_together': {('song_id', 'extracted_date')},
            },
        ),
    ]
