# Generated by Django 4.2.21 on 2025-05-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeSongViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=255, unique=True)),
                ('song_name', models.CharField(max_length=255)),
                ('view_count', models.BigIntegerField(default=0)),
                ('youtube_url', models.URLField(max_length=255)),
                ('extracted_date', models.DateField()),
                ('upload_date', models.DateField()),
            ],
        ),
    ]
