# Generated by Django 4.2.21 on 2025-07-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='youtubesongviewcount',
            table='youtube_crawling_data',
        ),
    ]
