# Generated by Django 4.2.21 on 2025-07-07 07:33

import crawling_view.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingPeriod',
            fields=[
                ('id', models.CharField(default=crawling_view.models.base.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('song_id', models.CharField(help_text='노래 ID (song_info.id 참조)', max_length=32)),
                ('start_date', models.DateField(help_text='크롤링 시작일')),
                ('end_date', models.DateField(help_text='크롤링 종료일')),
                ('is_active', models.BooleanField(default=True, help_text='활성화화 여부')),
            ],
            options={
                'db_table': 'crawling_period',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.CharField(default=crawling_view.models.base.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('genie_title', models.CharField(blank=True, help_text='지니 곡 제목', max_length=255, null=True)),
                ('genie_artist', models.CharField(blank=True, help_text='지니 아티스트명', max_length=255, null=True)),
                ('youtube_music_title', models.CharField(blank=True, help_text='유튜브 뮤직 곡 제목', max_length=255, null=True)),
                ('youtube_music_artist', models.CharField(blank=True, help_text='유튜브 뮤직 아티스트명', max_length=255, null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL (YouTube 크롤링용)', max_length=500, null=True)),
                ('melon_song_id', models.CharField(blank=True, help_text='멜론 곡 ID (Melon 크롤링용)', max_length=100, null=True, unique=True)),
            ],
            options={
                'db_table': 'song_info',
            },
        ),
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.CharField(default=crawling_view.models.base.generate_uuid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정시간')),
                ('song_id', models.CharField(help_text='노래 ID (song_info.id 참조)', max_length=32)),
                ('views', models.BigIntegerField(help_text='조회수 (정상값: 숫자, 미지원: -1, 오류: -999)')),
                ('listeners', models.BigIntegerField(help_text='청취자 수 (정상값: 숫자, 미지원: -1, 오류: -999)')),
                ('platform', models.CharField(choices=[('melon', 'Melon'), ('genie', 'Genie'), ('youtube', 'YouTube'), ('youtube_music', 'YouTube Music')], help_text='플랫폼명', max_length=20)),
            ],
            options={
                'db_table': 'crawling_data',
                'ordering': ['-created_at'],
                'unique_together': {('song_id', 'platform', 'created_at')},
            },
        ),
    ]
