# Generated by Django 4.2.21 on 2025-06-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubemusicsongviewcount',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='youtubemusicsongviewcount',
            name='youtube_music_url',
        ),
    ]
