# Generated by Django 4.2.21 on 2025-07-03 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_music', '0001_initial'),
    ]

    operations = [
    ]
