# Generated by Django 4.2.21 on 2025-06-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_music', '0002_remove_youtubemusicsongviewcount_upload_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubemusicsongviewcount',
            name='song_id',
        ),
    ]
