# Generated by Django 4.2.21 on 2025-07-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_music', '0002_auto_20250703_1632'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='youtubemusicsongviewcount',
            table='youtube_music_crawling_data',
        ),
    ]
