# Generated by Django 4.2.21 on 2025-06-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenieSongViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=255, unique=True)),
                ('artist_name', models.CharField(max_length=255)),
                ('song_name', models.CharField(max_length=255)),
                ('total_person_count', models.BigIntegerField(default=0)),
                ('total_play_count', models.BigIntegerField(default=0)),
                ('extracted_date', models.DateField()),
            ],
        ),
    ]
