# Generated by Django 4.2.21 on 2025-06-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geniesongviewcount',
            name='song_id',
        ),
    ]
